import Head from "next/head";
import Link from "next/link";

import styles from "./index.module.css";
import { Button, ButtonGroup, Card, Container } from '@chakra-ui/react'
import { useRouter } from "next/router";
import Login from "./login";
import axios from "axios";
import { env } from "~/env.mjs";

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container mt={8}>
        <Button colorScheme="blue" mb={4} onClick={()=>{
              router.push("/login")
        }}>LOGIN</Button>
        <Card p={4}>
          <ButtonGroup>
            <Button colorScheme="cyan" onClick={()=>{
              router.push("/ventas/new")
            }}>COTIZACIONES</Button>

            <Button colorScheme="cyan" onClick={()=>{
              router.push("/clientes")
            }}>CLIENTES</Button>
          </ButtonGroup>
        </Card>
      </Container>
    </>
  );
}
